version: '3.8'
volumes:
  redpanda: null
  
services:
  eda_webshop:
    container_name: eda-webshop
    build:
      dockerfile: Dockerfile
    image: eda-webshop:latest
    restart: always
    ports:
      - 1083:1083
    depends_on:
      - inventory
      - pricing
      - transport
      - order
      - user
      - payment
      - control-center

  inventory:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/inventory:/var/lib/mysql
    ports:
      - "3307:3306"

  pricing:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pricing
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/pricing:/var/lib/mysql
    ports:
      - "3308:3306"

  transport:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: transport
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/transport:/var/lib/mysql
    ports:
      - "3309:3306"

  order:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: order
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/order:/var/lib/mysql
    ports:
      - "3310:3306"

  user:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/user:/var/lib/mysql
    ports:
      - "3311:3306"

  payment:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payment
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./data/payment:/var/lib/mysql
    ports:
      - "3312:3306"
        
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"

  kafka-tools:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka-tools
    container_name: kafka-tools
    command: ["tail", "-f", "/dev/null"]
    network_mode: "host"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.4.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
